local_costmap:
  global_frame: /map
  robot_base_frame: /base_link
  observation_sources: laser_scan_sensor point_cloud_sensor0 point_cloud_sensor1
  laser_scan_sensor: {sensor_frame: laser_front, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true, expected_update_rate: 0.2}
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  map_type: costmap
#  transform_tolerance: 0.2
