scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 0
    max_angle: 175
    neighbors: 1
    window: 1
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.3
    upper_threshold: .inf
- name: specific_angle_filter1
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.43
    upper_angle: -1.38
- name: specific_angle_filter2
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: 1.38
    upper_angle: 1.43
#- name: footprint_filter
#  type: LaserScanFootprintFilter
#  params:
#    inscribed_radius: 0.24
#- name: interpolation
#  type: InterpolationFilter
#- name: timestamp_corrector
#  type: TimestampCorrector
#  params:
#    timestamp_offset: -0.2
